### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Artlands** [tactcomplabs/rev#116]
**Describe the bug**
REV cannot be compiled correctly in the **devel** branch. Error messages are like:
'''
/src/../include/RevNIC.h:116:9: error: expected identifier before string constant
         "revcpu",
         ^~~~~~~~
/src/../include/RevNIC.h:116:9: error: expected ‘,’ or ‘...’ before string constant
/src/../include/RevNIC.h:121:7: error: ISO C++ forbids declaration of ‘SST_ELI_REGISTER_SUBCOMPONENT’ with no type [-fpermissive]
       )
       ^
/src/../include/RevNIC.h:121:7: error: expected ‘;’ at end of member declaration
       )
       ^
'''

**To Reproduce**
- Run the building process in README.md
- SST-Core Version (12.0.1); g++; -std=c++1y -D__STDC_FORMAT_MACROS -fPIC -DHAVE_CONFIG_H -I/local/sstcore-12.0.1/include
- The last commit hash: [91c76ab](https://github.com/tactcomplabs/rev/commit/91c76abc9f197454d1b774773a5a86fde54318c1)
- The compiler utilized to build Rev: g++ (GCC) 8.5.0

**Expected behavior**
REV should be built correctly.

**Additional context**
Change the **SST_ELI_REGISTER_SUBCOMPONENT** marco to **SST_ELI_REGISTER_SUBCOMPONENT_DERIVED** will fix the issue. 
PanNet.h, RevCoProc.h, RevMemCtrl.h and RevNIC.h need fix.

**Comment by jleidel** [comment]
GCC 8.5.0 does not fully support C++17. You'll need to migrate to a newer version of GCC.  We are currently building internally with GCC 11.1.0.  Also, the `SST_ELI_REGISTER_SUBCOMPONENT_DERIVED` macro has been deprecated in SST 13.0.0.  The devel branch is correctly tracking the official release version of SST.  

See: https://sst-simulator.org/sstannouncements/2023/04/28/SST-v13.0.0-Released/
