### ISSUE TITLE
Fix all header references

### ISSUE THREAD

**Issue by jleidel** [tactcomplabs/rev#178]
**Describe the bug**
We currently have a very large number of `#include` statements that reference relative paths such as `../../common/path/to/foo`.  This needs to be fixed wholesale across the entire source tree.  Relative paths are inherently dangerous as they rely upon user/platform-specific environment configurations.

This is a simple fix by adding cmake logic to derive the path to the header files at build time, thus removing any environment-related issues.   

**To Reproduce**
See PR #176 

**Expected behavior**
Fix it

**Trace**
no trace

**Additional context**
No other context

**Comment by rkabrick** [comment]
https://github.com/tactcomplabs/rev/pull/182
