### ISSUE TITLE
P[0] Only Core 0 Executing Instructions despite Multiple HARTS in Configuration

### ISSUE THREAD

**Issue by aperdeus** [tactcomplabs/rev#184]
**Describe the bug**
I've encountered a bug where, despite having multiple HARTS  specified in the configuration file, only Core 0 is executing any instructions. 

Regression introduced probably by one of this commit:
3f34be58750d051be07de9331eb73c03fda1faef
9533c7f376328a37d750241eb07f49ffcb171bee
20670ec77ee9e9f7fffc4ce9c3454c7635eaa5f3
a90021af904b4358538b175983f41f95f5ffedde
28cd518a75e9b4aa661948d6f0d6ec67bf164b10
bcd8ab90996f763f31227626db4d2c39f1599ccc
d35d386b95dd98df9cdec9c07d0bacf9a91de891
( broken build repository status, preventing further progress in the bisecting)

**To Reproduce**

sst --version
SST-Core Version (-dev)
 sst-config --CXX
g++
sst-config --ELEMENT_CXXFLAGS
-std=c++17 -fPIC -DHAVE_CONFIG_H -I/home/aperdeus/git/sst-core/build/../sst-core-install/include

sst-core sha: 5e40e29e741aebbe7ef2e4666dbf8b562045b4ea

- The source code branch being used
devel
- The last commit hash
bfb2ebb64c5cda776bf81b2f8d5800b97b107647
- The compiler utilized to build Rev
clang
- The compiler utilized to build the test
clang
- The python or JSON simulation input
```
comp_cpu = sst.Component("cpu", "revcpu.RevCPU")
comp_cpu.addParams({
    "verbose": verbose_level,                   # Verbosity
    "numCores": 2,                           # Number of cores
    "clock": "1.0GHz",                          # Clock
    "memSize": 1024*1024*1024,                  # Memory size in bytes
    "machine": "[CORES:RV64IMAFD]",             # Core:Config;
    "startAddr": [0:0x000000000001199c,1:0x0000000000011960],                            # Starting address for cores
    "memCost": "[0:1:10]",                      # Memory loads required 1-10 cycles
    "program": program,                         # Target executable
    "splash": 0,                                # Display the splash message
    "args": rev_exe_args
})
```
- C/CXX test source (or mention which test in the current source tree failed)
```
#include<stdlib.h>
#include<assert.h>

#define ARR_SIZE 1024

#define STACK_SIZE 1024*100
int stack[STACK_SIZE];

volatile int c;

#define LOOP_SIZE (10000)

void busy_loop() {
    for(int i = 0; i < LOOP_SIZE; i++) {
        c++;
    }
}

int glob[2];

void test() {
    assert(glob[0] == 69);
    assert(glob[1] == 42);
}

int second() {
    glob[1] = 42;
    busy_loop();
    test();

    return 0;
}

void fix_stack () {
        asm ("mv sp, %0" :: "r" (stack+STACK_SIZE-1));
        second();
        return;
}

int main() {
    glob[0] = 69;
    busy_loop();
    test();

    return 0;
}
```
**Expected behavior**
Test should spawn 2 HARTS where each HART store value in global array then wait for enough time until store from other HART completed. Then both HARTS check the values of global array. This test should pass without assertion.

**Comment by rkabrick** [comment]
this program only ever has a single software thread created (ie. there is no work for the second hart to execute). This is the expected behavior. If you would like to have two Harts executing you need to use the `rev_pthread_create` function defined in the `syscalls.h` file. It has the same interface as the standard `pthread_create` function with the caveat that at this point we don't do anything with the `pthread_attr` struct.
