### ISSUE TITLE
simple constructor crash

### ISSUE THREAD

**Issue by kpgriesser** [tactcomplabs/rev#213]
**Describe the bug**
This is a bug affect c++ code which invoked a constructor for a small struct and crashes with the following message:

FATAL: RevCPU[cpu:ECALL_brk:309000]: Out of memory / Unable to expand system break (brk) to Addr = 0x0

**To Reproduce**

cd test/cxx/simple_struct
./run_simple_struct.sh

All issues must be accompanied by: 
- The version of SST utilized (`sst --version`; `sst-config --CXX`; `sst-config --ELEMENT_CXXFLAGS`)
  -std=c++17 -fPIC -DHAVE_CONFIG_H -I/Users/kgriesser/local/sstcore-13.0.0/include

- The source code branch being used
-- The last commit hash
  711e122 (HEAD -> devel, origin/devel)

- The compiler utilized to build Rev
  Apple clang version 15.0.0 (clang-1500.0.40.1)

- The compiler utilized to build the test
   riscv64-unknown-elf-c++ (g2ee5e430018-dirty) 12.2.0

- The python or JSON simulation input
- C/CXX test source (or mention which test in the current source tree failed)
  see test/cxx/simple_struct

**Expected behavior**
Test should pass ( no assertions firing )

**Trace**
Jumps into <_sbrk> and crashes

RevCPU[cpu:Render:291000]: Core 0; Hart 0; Thread 1; *I 0x185f2:44b000ef    jal     pc + 0xc4a	 ra<-0x185f6 pc<-0x1923c <_sbrk_r> 
RevCPU[cpu:Render:293000]: Core 0; Hart 0; Thread 1; *I 0x1923c:e0221141    c.addi  sp, -16	 0x3ffffb5c<-sp sp<-0x3ffffb4c 
RevCPU[cpu:Render:294000]: Core 0; Hart 0; Thread 1; *I 0x1923e:842ae022    c.sdsp  s0, 0(sp)	 0x3ffffb4c<-sp 0x27e88<-s0 [0x3ffffb4c,8]<-0x0000000000027e88 
RevCPU[cpu:Render:295000]: Core 0; Hart 0; Thread 1; *I 0x19240:852e842a    c.mv    s0, a0	 0x0<-zero 0x27740<-a0 s0<-0x27740 
RevCPU[cpu:Render:296000]: Core 0; Hart 0; Thread 1; *I 0x19242:a823852e    c.mv    a0, a1	 0x0<-zero 0x11f0<-a1 a0<-0x11f0 
RevCPU[cpu:Render:297000]: Core 0; Hart 0; Thread 1; *I 0x19244:7001a823    sw      zero, 1808(gp)	 0x28230<-gp 0x0<-zero [0x28940,4]<-0x00000000 
RevCPU[cpu:Render:298000]: Core 0; Hart 0; Thread 1; *I 0x19248:80efe406    c.sdsp  ra, 8(sp)	 0x3ffffb4c<-sp 0x185f6<-ra [0x3ffffb8c,8]<-0x00000000000185f6 
RevCPU[cpu:Render:299000]: Core 0; Hart 0; Thread 1; *I 0x1924a:444080ef    jal     pc + 0x8444	 ra<-0x1924e pc<-0x2168e <_sbrk> 
RevCPU[cpu:Render:301000]: Core 0; Hart 0; Thread 1; *I 0x2168e:72018693    addi    a3, gp, 1824	 0x28230<-gp a3<-0x28950 
RevCPU[cpu:Render:302000]: Core 0; Hart 0; Thread 1; *I 0x21692:11416298    c.ld    a4, 0(a3)	 0x28950<-a3 0x0000000000000000<-[0x28950,8] a4<-0x0 
RevCPU[cpu:Render:303000]: Core 0; Hart 0; Thread 1; *I 0x21694:e4061141    c.addi  sp, -16	 0x3ffffb4c<-sp sp<-0x3ffffb3c 
RevCPU[cpu:Render:304000]: Core 0; Hart 0; Thread 1; *I 0x21696:87aae406    c.sdsp  ra, 8(sp)	 0x3ffffb3c<-sp 0x1924e<-ra [0x3ffffb7c,8]<-0x000000000001924e 
RevCPU[cpu:Render:305000]: Core 0; Hart 0; Thread 1; *I 0x21698:eb1987aa    c.mv    a5, a0	 0x0<-zero 0x11f0<-a0 a5<-0x11f0 
RevCPU[cpu:Render:306000]: Core 0; Hart 0; Thread 1; *I 0x2169a:0893eb19    c.bnez  a4, pc + 22	 0x0<-a4 0x0<-zero 
RevCPU[cpu:Render:307000]: Core 0; Hart 0; Thread 1; *I 0x2169c:0d600893    li      a7, 214	 0x0<-zero a7<-0xd6 
RevCPU[cpu:Render:308000]: Core 0; Hart 0; Thread 1; *I 0x216a0:00734501    c.li    a0, 0	 0x0<-zero a0<-0x0 
FATAL: RevCPU[cpu:ECALL_brk:309000]: Out of memory / Unable to expand system break (brk) to Addr = 0x0
SST Fatal Backtrace Information:
    0 : 0   sstsim.x                            0x00000001041c4ca0 _ZNK3SST6Output5fatalEjPKcS2_iS2_z + 576
    1 : 1   librevcpu.dylib                     0x00000001084a96f0 _ZN3SST6RevCPU7RevProc9ECALL_brkERNS0_7RevInstE + 120
    2 : 2   librevcpu.dylib                     0x00000001084b5c28 _ZN3SST6RevCPU7RevProc9ExecEcallERNS0_7RevInstE + 360
    3 : 3   librevcpu.dylib                     0x00000001084b5980 _ZN3SST6RevCPU7RevProc9ClockTickEy + 2908
    4 : 4   librevcpu.dylib                     0x000000010845c72c _ZN3SST6RevCPU6RevCPU9clockTickEy + 200
    5 : 5   sstsim.x                            0x000000010417a760 _ZN3SST5Clock7executeEv + 252
    6 : 6   sstsim.x                            0x00000001041e0074 _ZN3SST15Simulation_impl3runEv + 496
    7 : 7   sstsim.x                            0x000000010416aa4c _ZL16start_simulationjR15SimThreadInfo_tRN3SST4Core10ThreadSafe7BarrierE + 2988
    8 : 8   sstsim.x                            0x0000000104167174 main + 7608
    9 : 9   dyld                                0x00000001842a10e0 start + 2360

**Additional context**

Here is the disassembly for the failing code:

000000000002168e <_sbrk>:
   2168e:       72018693                add     a3,gp,1824 # 28950 <heap_end.0>
   21692:       6298                    ld      a4,0(a3)
   21694:       1141                    add     sp,sp,-16
   21696:       e406                    sd      ra,8(sp)
   21698:       87aa                    mv      a5,a0
   2169a:       eb19                    bnez    a4,216b0 <_sbrk+0x22>
   2169c:       0d600893                li      a7,214
   216a0:       4501                    li      a0,0
   216a2:       00000073                ecall. <--- HERE

**Comment by donofrio** [comment]
while we await a sbrk fix I have updated the test to show one example of an overloaded new and delete function that will allow c++ to work

**Comment by kpgriesser** [comment]
this test is now passing but I think there is still an issue. I'll close this and open a new one with a different reproducer.

**Comment by kpgriesser** [comment]
creating another reproducer

**Comment by leekillough** [comment]
There was a lot of memory corruption in the command-line argument handling.
