### ISSUE TITLE
Argument passing / atoi conversion  sensitivity to compiler output

### ISSUE THREAD

**Issue by kpgriesser** [tactcomplabs/rev#214]
**Describe the bug**
 The test incorrectly attempts to read from location 0 during command line argument parsing. This test is sensitive to how the code is compiled so a passing and failing case are provided.

**To Reproduce**

cd test/argc_bug
make clean; make
Comment out line 20 of argc_bug.c to provided a passing case to compare against.
argc_bug.c:20 #define INDUCE_ARGC_BUG

All issues must be accompanied by: 
- The version of SST utilized (`sst --version`; `sst-config --CXX`; `sst-config --ELEMENT_CXXFLAGS`)
SST-Core Version (13.0.0)

- The source code branch being used
- The last commit hash
2f2bda7 (HEAD -> devel, origin/devel) argc bug test

- The compiler utilized to build Rev
Apple clang version 15.0.0 (clang-1500.0.40.1)

- The compiler utilized to build the test
riscv64-unknown-elf-g++ (g2ee5e430018-dirty) 12.2.0

- The python or JSON simulation input
- C/CXX test source (or mention which test in the current source tree failed)

cd test/argc_bug
make clean; make

Comment out line 20 of argc_bug.c to provided a passing case to compare against.
argc_bug.c:20 #define INDUCE_ARGC_BUG

**Expected behavior**

Test executes with no exceptions

**Trace**
Failing trace summary:
-----------------------
The stack location at 0x3ffffbac is written with a zero and later used as a pointer into memory:

<_strtol_l.constprop.0>
[28000] *I 0x103c8:ec061101    c.addi  sp, -32           0x3ffffbcc<-sp sp<-0x3ffffbac
[29000] *I 0x103ca:e822ec06    c.sdsp  ra, 24(sp)        0x3ffffbac<-sp 0x10298<-ra [0x3ffffc6c,8]<-0x0000000000010298
[30000] *I 0x103cc:e426e822    c.sdsp  s0, 16(sp)        0x3ffffbac<-sp 0x3ffffb94<-s0 [0x3ffffc2c,8]<-0x000000003ffffb94
[31000] *I 0x103ce:e04ae426    c.sdsp  s1, 8(sp)         0x3ffffbac<-sp 0x4<-s1 [0x3ffffbec,8]<-0x0000000000000004
[32000] *I 0x103d0:0793e04a    c.sdsp  s2, 0(sp)         0x3ffffbac<-sp 0x0<-s2 [0x3ffffbac,8]<-0x0000000000000000

The subsequent read
[209000] *I 0x10148:01843503    ld      a0, 24(s0)       0x3ffffb94<-s0 0x0000000000000000<-[0x3ffffbac,8] a0<-0x0

Eventually leading to this instruction causing seg fault
        103ea:  0008c703                lbu     a4,0(a7)

FATAL: RevCPU[cpu:CalcPhysAddr:234000]: Segmentation Fault: Virtual address 0x0 (PhysAddr = 0xffffffffffffffff) was not found in any mem segments
SST Fatal Backtrace Information:
    0 : 0   sstsim.x                            0x00000001040acca0 _ZNK3SST6Output5fatalEjPKcS2_iS2_z + 576
    1 : 1   librevcpu.dylib                     0x00000001089bf348 _ZN3SST6RevCPU6RevMem12CalcPhysAddrEyy + 824
    2 : 2   librevcpu.dylib                     0x00000001089c2164 _ZN3SST6RevCPU6RevMem7ReadMemEjymPvRKNS0_6MemReqENS0_7RevFlagE + 88
    3 : 3   librevcpu.dylib                     0x0000000108a20830 _ZN3SST6RevCPU6RevMem7ReadValIhEEbjyPT_RKNS0_6MemReqENS0_7RevFlagE + 68
    4 : 4   librevcpu.dylib                     0x0000000108a431f0 _ZN3SST6RevCPU4loadIhEEbPNS0_10RevFeatureEPNS0_10RevRegFileEPNS0_6RevMemENS0_7RevInstE + 10\
44
    5 : 5   librevcpu.dylib                     0x00000001089b3448 _ZN3SST6RevCPU6RevExt7ExecuteEjRKNS0_7RevInstEtPNS0_10RevRegFileE + 520
...

Comparison of passing and failing test cases:

In the passing test case the initial stack pointer is initialized with 48 bytes, presumably because the arg[] values are used in the passing case and optimize\
d out in the failing case.

In the passing case the location 0x3ffffbac has a non-zero value.

Passing case: [214000] *I 0x1015c:01843503    ld      a0, 24(s0) 0x3ffffb94<-s0 0x000000003ffffffe<-[0x3ffffbac,8] a0<-0x3ffffffe
Passing Case: [239000]:*I 0x1045e:0008c703    lbu     a4, 0(a7)  0x3ffffffe<-a7 0x32<-[0x3ffffffe,1] a4<-0x32

Strangely, for the passing case, I cannot find where 0x3fffffe is written into location 0x3ffffbac based on the trace. ( I'd like to understand where this val\
ue gets into memory but need to work on other things)

**Comment by kpgriesser** [comment]
This issue is becoming higher priority. I'm not sure if the problem is the args or the atoi function misbehaving.

**Comment by jleidel** [comment]
Is this C or CXX?

**Comment by kpgriesser** [comment]
It is CXX. The source suffix should be changed to .cc.

**Comment by jleidel** [comment]
ok, perfect.  I think we can relegate this to being CXX only.

**Comment by kpgriesser** [comment]
Looking more like a memory corruption issue.  In updown-accel/ud-sys-devel I have a more robust workaround by providing a system call that gives back each argv from the internally stored vector<string>. If this would be helpful in the main rev repo I can create a PR for it.  
Usage:
  int argv1 = rev::atoi_argv(1);
  int argv2 = rev::atoi_argv(2);
  int argv3 = rev::atoi_argv(3);

**Comment by kpgriesser** [comment]
I added more checks in the test and provided an annotated trace that shows where argv[2][0] is referenced to check it's initial char value and where the reference is clobbered in the atoi code. Subsequent usage of the value referenced leads to the crash. See argc_bug.trace_annotated.  Search for '###' for comments and '!!!' for errant behavior. This was run using macOS but the Ubuntu run is similar.

**Comment by kpgriesser** [comment]
Verified PR #288 fixes this bug. Will close when PR is approved and merged into devel branch

**Comment by kpgriesser** [comment]
confirmed
