### ISSUE TITLE
Errors when setting up multiple cores

### ISSUE THREAD

**Issue by Artlands** [tactcomplabs/rev#23]
While setting up multiple cores, the parameters for machine models, start address, instruction table and memory cost can not be parsed correctly. It seems that InitXXX functions in RevOpts.cc have bugs. Moving `std::vector<std::string> vstr;` inside the for loop can solve the issue.

**Comment by jleidel** [comment]
There are a number of relevant changes and bug fixes on the `devel` branch that have not yet been merged to master.  In the mean time, using `std::string::clear()` is a better solution as it avoids unnecessary heap expansion issues when loading large numbers of cores.  See Commit 9ecd180.  

In the future, if you see issues with specific items, its useful to post the command line options utilized and/or attach configuration graphs.

**Comment by jleidel** [comment]
fix has been merged to master
