### ISSUE TITLE
c.addi16sp instruction is incorrectly printed as c.lui by Rev Tracer

### ISSUE THREAD

**Issue by leekillough** [tactcomplabs/rev#260]
**Describe the bug**

When `rd == x2` (stack pointer), the `c.lui` instruction should be printed as a `c.addi16sp` instruction. When `rd == 0`, it is a reserved hint instruction.

**To Reproduce**

Latest `devel`

**Expected behavior**

Rev Tracer should print `c.addi16sp` when `rd == x2`.

**Trace**

```
RevCPU[cpu:GetNextHartToDecodeID:41463000]: Core 0; Hart switch from 0 to 0
RevCPU[cpu:FetchAndDecodeInst:41463000]: Core 0; Hart 0; Thread 1; PC:InstPayload = 0x1e130:0x80826125
RevCPU[cpu:Render:41463000]: Core 0; Hart 0; Thread 1; *I 0x1e130:80826125    c.lui %rd, $imm    0x3fffea7c<-x2 x2<-0x3fffeadc
```
**Additional context**

Since loading the upper part of the stack pointer with a compressed instruction is uncommon, `c.lui` with `rd == x2` was reserved as an instruction to add to `x2` instead of loading an upper immediate.

**Comment by kpgriesser** [comment]
see comments in #261. We should agree on how to handle the default internal mnemonic.   Building with spike give the expected mnemonic.

// REV_USE_SPIKE==OFF
RevCPU[cpu0:Render:74729000]: Core 0; Hart 0; Thread 1; *I 0x1014a:80826105    c.lui %rd, $imm	 0x3fffffffbdc<-x2 x2<-0x3fffffffbfc 
// REV_USE_SPIKE==ON
RevCPU[cpu0:Render:74729000]: Core 0; Hart 0; Thread 1; *I 0x1014a:80826105    c.addi16sp sp, 32	 0x3fffffffbdc<-sp sp<-0x3fffffffbfc
