### ISSUE TITLE
Tracer is printing compressed register move instructions as c.jr instructions

### ISSUE THREAD

**Issue by leekillough** [tactcomplabs/rev#261]
**Describe the bug**

When a compressed register <- register copy ( `c.mv` ) is encountered, Rev Tracer prints it as a `c.jr` instruction.

**To Reproduce**

Latest `devel` 

**Expected behavior**

It should print `c.mv` when `rs2 != 0`

**Trace**

```
RevCPU[cpu:GetNextHartToDecodeID:41465000]: Core 0; Hart switch from 0 to 0
RevCPU[cpu:FetchAndDecodeInst:41465000]: Core 0; Hart 0; Thread 1; PC:InstPayload = 0x19fce:0xe90187aa
RevCPU[cpu:Render:41465000]: Core 0; Hart 0; Thread 1; *I 0x19fce:e90187aa    c.jr %rs1  0x0<-x0 0x0<-x10 x15<-0x0
```
```
RevCPU[cpu:GetNextHartToDecodeID:41467000]: Core 0; Hart switch from 0 to 0
RevCPU[cpu:FetchAndDecodeInst:41467000]: Core 0; Hart 0; Thread 1; PC:InstPayload = 0x19fd2:0xf0ef8522
RevCPU[cpu:Render:41467000]: Core 0; Hart 0; Thread 1; *I 0x19fd2:f0ef8522    c.jr %rs1  0x0<-x0 0x90<-x8 x10<-0x90
```

**Additional context**

`C.MV` copies the value in register `rs2` into register `rd`. `C.MV` expands into `add rd, x0, rs2`. `C.MV`
is only valid when `rs2 != x0`; the code points with `rs2 = x0` correspond to the `C.JR` instruction. The
code points with `rs2 != x0` and `rd = x0` are HINTs.

`C.MV` expands to a different instruction than the canonical `MV` pseudoinstruction, which instead
uses `ADDI`. Implementations that handle `MV` specially, e.g. using register-renaming hardware,
may find it more convenient to expand `C.MV` to `MV` instead of `ADD`, at slight additional hardware
cost.

**Comment by donofrio** [comment]
Is this using tracer in conjunction with Spike?

**Comment by leekillough** [comment]
No

**Comment by kpgriesser** [comment]
When not building without linking to the Spike disassembler the tracer simply degrades to using the RevInstEntry.mnemonic field (RevInstTable.h:130).  I was avoiding changing this as I wasn't how it might affect others.

For reference, when building with Spike it appears to get it right.

// Compiled with REV_USE_SPIKE=OFF
RevCPU[cpu0:Render:15189000]: Core 0; Hart 0; Thread 1; *I 0x1011e:e03e850a    c.jr %rs1	 0x0<-x0 0x3fffffffbdc<-x2 x10<-0x3fffffffbdc 
// Compiled with REV_USE_SPIKE=ON
RevCPU[cpu0:Render:15189000]: Core 0; Hart 0; Thread 1; *I 0x1011e:e03e850a    c.mv    a0, sp	 0x0<-zero 0x3fffffffbdc<-sp a0<-0x3fffffffbdc

I guess at the point of rendering the trace line we could further qualify what is printed based on the register and data fields. I don't have a good feel for how many special cases there are. A handful of special cases may not be a big deal but if it becomes supporting our own disassembler I'd rather just tell people to build with spike support.
