### ISSUE TITLE
AUIPC simulation bug

### ISSUE THREAD

**Issue by Artlands** [tactcomplabs/rev#27]
The `auipc` instruction for RV64 has a bug when encountering negative immediates and it generates an incorrect address. The bug is because of that it did not sign-extend the value after bit shifting.

To reproduce the issue, compile the following C program with `riscv64-unknown-elf-gcc -march=rv64imafd`. Since we have some issues with decoding the compressed instruction, the test is compiled without the `compressed` option. 

```c
#include <stdio.h>
int main( int argc, char **argv ){
  printf( "Test Print...\n" );
}
```

Here is a snippet of the simulation output:
![image](https://user-images.githubusercontent.com/31781106/215850596-00b760a5-1424-4f3e-8bd4-dd868c4b093c.png)

When investigating in the disassembled object file, we can see that the correct jump address should be `0x10fe0` instead of `0x100010fe0`.

```assembly
   1297c:	00050913          	mv	s2,a0
   12980:	00048513          	mv	a0,s1
   12984:	ffffe097          	auipc	ra,0xffffe
   12988:	65c080e7          	jalr	1628(ra) # 10fe0 <_malloc_r>
   1298c:	02051063          	bnez	a0,129ac <__smakebuf_r+0x98>
   12990:	01041783          	lh	a5,16(s0)
```
Sign-extending the bit shifted immediate will solve the issue:

```c
  static bool auipc(RevFeature *F, RevRegFile *R,RevMem *M, RevXbgas *Xbgas, RevInst Inst) {
        uint64_t tmp;
        if( F->IsRV32() ){
          R->RV32[Inst.rd] = 0x00;
          R->RV32[Inst.rd] = (Inst.imm << 12) + dt_u32(R->RV32_PC,32);
          R->RV32_PC += Inst.instSize;
        }else{
          SEXT(tmp, Inst.imm << 12, 32);
          R->RV64[Inst.rd] = 0x00;
          R->RV64[Inst.rd] = tmp + R->RV64_PC;
          R->RV64_PC += Inst.instSize;
        }
        return true;
      }
```

**Comment by jleidel** [comment]
Will test in our current dev branch and report back

**Comment by jleidel** [comment]
fix merged to devel
