### ISSUE TITLE
[FEATURE REQUEST] Documentation 

### ISSUE THREAD

**Issue by rkabrick** [tactcomplabs/rev#273]
**Rev Feature Request**
I tried building the documentation for Rev for the first time and was unable to do so. I know we have the Doxygen skeleton kind of throughout the repo but `-DBUILD_DOCUMENTATION` ends in the following error. 

<img width="725" alt="image" src="https://github.com/tactcomplabs/rev/assets/31963805/d146aca4-03d0-42bc-8165-27a45c47e6c0">

**Version of SST**
N/A

**Additional context**
See above

**Comment by jleidel** [comment]
In progress

**Comment by jleidel** [comment]
Fix in 0d69918

**Comment by jleidel** [comment]
confirmed fix in CI
