### ISSUE TITLE
Store-conditional Interface (RevMem::SCBase) does not handle Len and Target correctly

### ISSUE THREAD

**Issue by Artlands** [tactcomplabs/rev#312]
**Describe the bug**
The Len in RevMem::SCBase should only be either 4 or 8 in bytes, not 32 or 64 in bits. 
While writing zeros to the Target, the implementation does not make sense.  

**To Reproduce**
A simple test does not catch this bug. I found this issue when implementing remote lr/sc instructions in the xBGAS project.

**Additional context**
Fix: convert Len to TotalBits, i.e. Len*8, and use the TotalBits for comparing A with B.

Set Target to 0 could be like the following:
```     // write zeros to target
uint8_t* Tmp = reinterpret_cast<uint8_t*>( Target );
for( unsigned i = 0; i < Len; i++ ) {
   Tmp[i] = 0x0;
}
```

**Comment by leekillough** [comment]
Words are measured in `Len` bytes, and must be `1`, `2`, `4` or `8` bytes.

4 bytes = 32 bits
8 bytes = 64 bits
So there is no difference whether we count in bytes or bits.

But this code does not look safe:
```c++
      // write zeros to target
      for( unsigned i = 0; i < Len; i++ ) {
        uint64_t* Tmp = reinterpret_cast<uint64_t*>( Target );
        Tmp[i]        = 0x0;
      }
```
`Tmp[i]` is indexing `uint64_t` values by the subscript from `0` to `Len-1`. It was probably intended to be more like this:
```c++
      // write zeros to target
      char* Tmp = reinterpret_cast<char*>( Target );
      for( unsigned i = 0; i < Len; i++ ) {
        Tmp[i]        = 0x0;
      }
```
But a `memset( Target, 0, Len );` is much simpler, and does not need `reinterpret_cast`.

Except when changing the signedness of an integral type, or casting to different aggregate types which have common initial members, or casting to a `char*` or `unsigned char*`, it violates [strict aliasing](https://en.cppreference.com/w/cpp/language/reinterpret_cast#Type_aliasing) to dereference a pointer after casting to a different type.

I'll clean up the code.
