### ISSUE TITLE
Application with std::string exits prematurely

### ISSUE THREAD

**Issue by marcinkoss** [tactcomplabs/rev#39]
Application with below source code exits prematurely.

#include <string>
int main() {
        std::string fname("/asdf/asdf/asdf/as/dfasd/f");
        return 0;
}

To reproduce:
1) use any riscv c++ compiler of your choice (gnu, llvm) and compile:
riscv64-linux-gnu-g++ tc1.c -static -o tc1.exe
below logs are generated with gnu g++
2) run binary in REV model with configuration provided
[rev_config.txt](https://github.com/tactcomplabs/rev/files/11273015/rev_config.txt)
REV_EXE=tc1.exe timeout 10s sst ../rev_config.txt
3) Check execution trace (see attached file with parsed trace to asm instruction)
[trace.txt](https://github.com/tactcomplabs/rev/files/11273093/trace.txt)

Program execution stops on 'ret' instruction however that is not end of the program

**Comment by jleidel** [comment]
what branch did you test this against?

**Comment by marcinkoss** [comment]
main, but on devel it does not work as well. instead of REV shut down 'ret' jumps somewhere and start executing garbage.

on devel:
RevCPU[cpu:ClockTick:95000]: Core 0 ; ThreadID 0; Retiring PC= 0x10ade
RevCPU[cpu:DecodeInst:96000]: Core 0 ; Thread 0; PC:InstPayload = 0x10ae0:0x11018082
RevCPU[cpu:ClockTick:96000]: Core 0 ; Thread 0; Executing PC= 0x10ae0
**RevCPU[cpu:ClockTick:96000]: Core 0 ; ThreadID 0; Retiring PC= 0x10ae0**  --------- this is 'RET' instruction
RevCPU[cpu:DecodeInst:98000]: Core 0 ; Thread 0; PC:InstPayload = 0x3ffff3cc:0x0
RevCPU[cpu:ClockTick:98000]: Core 0 ; Thread 0; Executing PC= 0x3ffff3cc
RevCPU[cpu:ClockTick:98000]: Core 0 ; ThreadID 0; Retiring PC= 0x3ffff3cc
RevCPU[cpu:DecodeInst:99000]: Core 0 ; Thread 0; PC:InstPayload = 0x3ffff3ce:0x0

Last devel commit:
commit bd85b46cae6ff54754b259cf6085ee2e1b3a1a15 (HEAD -> rev-devel, origin/rev-devel)
Merge: a8a22e6 04cfd0c
Author: jleidel <jleidel@users.noreply.github.com>
Date:   Fri Apr 14 07:19:47 2023 -0500

    Merge pull request #36 from tactcomplabs/ISAFixes

    Isa fixes

**Comment by donofrio** [comment]
I can confirm we can reproduce this - looking into it

**Comment by ukasz** [comment]
Now the aformentioned example fails due to lack of brk syscall.

**Comment by marcinkoss** [comment]
Original issue is fixed, missing syscalls are tracked separately
