### ISSUE TITLE
AMOADD atomic ends up in an infinite loop

### ISSUE THREAD

**Issue by ukasz** [tactcomplabs/rev#43]
The following code is looping indefinetly on a basic config (ex2 config, devel branch):
```
int main() {
        std::atomic<int> a;
        a = 0;
        a++;
}
```
a++ is the offending instruction:

RevCPU[cpu:DecodeInst:11106000]: Core 0 ; Thread 0; PC:InstPayload = 0x11468:0x6b5252f
RevCPU[cpu:ClockTick:11106000]: Core 0 ; Thread 0; Executing PC= 0x11468
RevCPU[cpu:ClockTick:11106000]: Core 0 ; ThreadID 0; Retiring PC= 0x11468

   11468: 2f 25 b5 06   amoadd.w.aqrl   a0, a1, (a0)

**Comment by donofrio** [comment]
This appears to be an issue with the sc.w instruction - fixed and will be in the next push to devel
