### ISSUE TITLE
Infinite loop on std::sort

### ISSUE THREAD

**Issue by ukasz** [tactcomplabs/rev#44]
The following code compiled with clang16.0 is never ending when N is  24 or larger.
```
//clang++ -march=rv64imafd -o rand.exe rand.cpp
#include <algorithm>

//23 ok
//24 infinite loop
#define N 24

unsigned long long mem[N];

int main() {
        std::sort(mem, mem + N);
}
```

ELF executable attached: [sort.zip](https://github.com/tactcomplabs/rev/files/11276613/sort.zip)

**Comment by jleidel** [comment]
related to Issue #39

**Comment by donofrio** [comment]
Working with latest devel branch (N == 256 completes successfully)

**Comment by ukasz** [comment]
Fix confirmed, closing
