### ISSUE TITLE
Infinite loop on strlen

### ISSUE THREAD

**Issue by marcinkoss** [tactcomplabs/rev#45]
Compile
riscv64-linux-gnu-gcc tc3.cpp -static -o tc3.exe
and run program:

int main() {
        char* txt = "some  really nice text";
        int l = strlen(txt);
        return 0;
}

or alternatively:
int main() {
        char* txt = "some  really nice text";

        int i =0;
        while ( *txt++ != '\0')
                i++;
        return 0;
}

REV enters infinite loop and never finishes execution.

**Comment by donofrio** [comment]
This test is now working in the latest devel branch using the unknown-elf c or c++ compiler

**Comment by ukasz** [comment]
Fix confirmed, can be closed.
