### ISSUE TITLE
Dual memset fail

### ISSUE THREAD

**Issue by ukasz** [tactcomplabs/rev#51]
The code listed below does not work properly.
Tested on devel branch (84260da280304c05493da2d7ee18bdeb5a01f39a) and standard config.
First memset produces correct results, but we hit an assert after a second memset call, which is unexpected.

```
#include <string.h>
#define assert(x) if (!(x)) { asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); }
#define N (1024)
char mem[N];

int main() {
         memset(mem, 42, N);
         for(int i = 0; i < N; i++)
             assert(mem[i] == 42);
         memset(mem, 0, N);
         for(int i = 0; i < N; i++)
                 assert(mem[i] == 0);
        return 0;
}
```

**Comment by donofrio** [comment]
Issue determined to be a problem with the store instruction - fix pushed to latest devel branch

**Comment by ukasz** [comment]
Fix confirmed, can be closed.
