### ISSUE TITLE
[P0] Atomic increment doesn't work

### ISSUE THREAD

**Issue by ukasz** [tactcomplabs/rev#56]
We observe cpp atomic operations to fail on data sizes wider than char (tested sha: cd753f7 compiled with LLVM)
Simplest example of such behavior is depicted below.
```
#include <atomic>
#define assert(x) if (!(x)) { asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); }

int main() {
        std::atomic<int> a;
        a = 0;
        a++;
        assert(a == 1);
}
```

**Comment by ukasz** [comment]
Even if atomic operations cannot be "atomic" yet, we would like to see their behavior emulated, so they are functionally working on a single thread.

**Comment by jleidel** [comment]
the single threaded versions are functionally emulated using only the embedded memory infrastructure; currently adding support for these on the `amo` branch

**Comment by jleidel** [comment]
fixed
