### ISSUE TITLE
Issues of Pipeline when using memHierarchy

### ISSUE THREAD

**Issue by Artlands** [tactcomplabs/rev#63]
The load instructions could retire early before the data is committed to the registers. 

To reproduce the issue, I use the following test program and use the same configuration file as [memh_2](https://github.com/tactcomplabs/rev/blob/devel/test/memh_2/rev-test-memh2.py), which uses memHierarchy as the memory backend. The program is compiled with riscv64-unknown-elf-gcc (12.2.0).

```
int main(int argc, char **argv){
  int i = 9;
  int j = 10;
  i = i + j;
  if( i == 19 )
    while(1);
  else
    return i;
}
```
The code will not terminate if all load instructions work correctly. However, the simulation ends in about 453 ns of the simulated time.

If the memory backend is switched to the built-in memory, it works as expected.

**Comment by jleidel** [comment]
fixed on devel
