### ISSUE TITLE
`fd` variable defs inconsistent across syscalls

### ISSUE THREAD

**Issue by jleidel** [tactcomplabs/rev#77]
The `ECALL_read` and `ECALL_close` utilize inconsistent definitions for the temporary file descriptor variable.  This should be made consistent.  

See line 2942 & line 2984 of RevProc.cc

**Comment by rkabrick** [comment]
[Fixed](https://github.com/tactcomplabs/rev/commit/9bb3d35ab89467ad773d544ed614ae51927cc996)
