### ISSUE TITLE
[P1] Program execution exits prematurely.

### ISSUE THREAD

**Issue by marcinkoss** [tactcomplabs/rev#86]
Use LLVM toolchain, build & compile below code snippet.
```
CXX=$(TIGRE_TOOLCHAIN_INSTALL)/bin/clang++
ARCH=rv64imafd
$(CXX) -march=$(ARCH) -O0 -o program.exe
```

```
#include <iostream>

using namespace std;

int vd  =5;
int main() {

  shared_ptr<int> p= make_shared<int>(vd);
  cout << std::endl;

  return 0;
}
```

Result: execution of program reaches 'jalr' instruction in which it jumps to address 0x0 and stop running. This is not issue with jalr instruction itself but for some reason memory content is corrupted and data read from stack are not correct which results into jalr behaviour.

**Comment by marcinkoss** [comment]
Attached logs (objdump and parsed log file)
[logs.zip](https://github.com/tactcomplabs/rev/files/12158925/logs.zip)

**Comment by marcinkoss** [comment]
ee attached image. Value popped from stack is equal to addi/sb instructions.
![jalr](https://github.com/tactcomplabs/rev/assets/33027385/c1669d72-5220-43ce-91cb-fcf1f2ac3827)

**Comment by ukasz** [comment]
Tested on devel, no longer an issue and can be closed.
