### ISSUE TITLE
[P1] RV64UM isa tests fails

### ISSUE THREAD

**Issue by ukasz** [tactcomplabs/rev#87]
We observe multiple fails while running RV64UM ISA tests suite:
https://github.com/riscv-software-src/riscv-tests/tree/master/isa/rv64um

This task is a superset of #84 #85 to avoid creating more related issues.

**Comment by donofrio** [comment]
RV64UM instructions should be passing in latest devel [051e164]. Asm tests added

**Comment by leekillough** [comment]
#115 should have fixed a lot of these issues. Please close this issue if it's verified fixed.

**Comment by ukasz** [comment]
Fix confirmed.
