### ISSUE TITLE
[P2] RV64I fence instruction not implemented

### ISSUE THREAD

**Issue by marcinkoss** [tactcomplabs/rev#88]
Fence test from [riscv](https://github.com/riscv-software-src/riscv-tests) does not pass.
Checked in REV source code and this instruction is not implemented.

**Comment by jleidel** [comment]
`fence` is implemented in RV32I.h from ~/include/insns/

**Comment by marcinkoss** [comment]
True - I should be more clear - it does nothing. From RV32I.h:
```
      static bool fence(RevFeature *F, RevRegFile *R,RevMem *M,RevInst Inst) {
        if( F->IsRV32() ){
          R->RV32_PC += Inst.instSize;
        }else{
          R->RV64_PC += Inst.instSize;
        }
        return true;  // temporarily disabled
      }
```

**Comment by jleidel** [comment]
Added in 4ab4cfd

**Comment by jleidel** [comment]
fixed
